# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\AddWorker.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(444, 316)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 47, 13))
        self.label_6.setObjectName("label_6")
        self.workerName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.workerName.setGeometry(QtCore.QRect(130, 60, 261, 20))
        self.workerName.setObjectName("workerName")
        self.workerEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.workerEmail.setGeometry(QtCore.QRect(130, 90, 261, 20))
        self.workerEmail.setObjectName("workerEmail")
        self.workerPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.workerPassword.setGeometry(QtCore.QRect(130, 120, 261, 20))
        self.workerPassword.setObjectName("workerPassword")
        self.gender = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(130, 150, 261, 20))
        self.gender.setObjectName("gender")
        self.age = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.age.setGeometry(QtCore.QRect(130, 180, 261, 20))
        self.age.setObjectName("age")
        self.addWorkerDoneBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addWorkerDoneBtn.setGeometry(QtCore.QRect(10, 220, 75, 23))
        self.addWorkerDoneBtn.setObjectName("addWorkerDoneBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 444, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "New Worker"))
        self.label.setText(_translate("MainWindow", "Add Worker Details:"))
        self.label_2.setText(_translate("MainWindow", "Worker Name:"))
        self.label_3.setText(_translate("MainWindow", "Temporary Pass:"))
        self.label_4.setText(_translate("MainWindow", "Email:"))
        self.label_5.setText(_translate("MainWindow", "Gender:"))
        self.label_6.setText(_translate("MainWindow", "Age:"))
        self.addWorkerDoneBtn.setText(_translate("MainWindow", "Done"))
