# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\NGODetails.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NGODetails(object):
    def setupUi(self, NGODetails):
        NGODetails.setObjectName("NGODetails")
        NGODetails.resize(800, 835)
        self.centralwidget = QtWidgets.QWidget(parent=NGODetails)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 100, 741, 251))
        self.groupBox.setObjectName("groupBox")
        self.listWidget = QtWidgets.QListWidget(parent=self.groupBox)
        self.listWidget.setEnabled(False)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 711, 192))
        self.listWidget.setObjectName("listWidget")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(110, 30, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 60, 341, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        NGODetails.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NGODetails)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        NGODetails.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NGODetails)
        self.statusbar.setObjectName("statusbar")
        NGODetails.setStatusBar(self.statusbar)

        self.retranslateUi(NGODetails)
        QtCore.QMetaObject.connectSlotsByName(NGODetails)

    def retranslateUi(self, NGODetails):
        _translate = QtCore.QCoreApplication.translate
        NGODetails.setWindowTitle(_translate("NGODetails", "NGO-DETAILS"))
        self.label.setText(_translate("NGODetails", "NAME OF NGO:"))
        self.label_2.setText(_translate("NGODetails", "OWNED BY:"))
        self.groupBox.setTitle(_translate("NGODetails", "WORK DONE TILL DATE:"))
