# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\NGOLogin.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NGOScreen(object):
    def setupUi(self, NGOScreen):
        NGOScreen.setObjectName("NGOScreen")
        NGOScreen.resize(442, 343)
        self.centralwidget = QtWidgets.QWidget(parent=NGOScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 91, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_4.setObjectName("label_4")
        self.ngoUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ngoUsername.setGeometry(QtCore.QRect(90, 50, 271, 20))
        self.ngoUsername.setObjectName("ngoUsername")
        self.ngoPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ngoPassword.setGeometry(QtCore.QRect(90, 80, 271, 20))
        self.ngoPassword.setObjectName("ngoPassword")
        self.NGOEnterButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.NGOEnterButton.setGeometry(QtCore.QRect(10, 110, 75, 23))
        self.NGOEnterButton.setObjectName("NGOEnterButton")
        NGOScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NGOScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 442, 24))
        self.menubar.setObjectName("menubar")
        NGOScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NGOScreen)
        self.statusbar.setObjectName("statusbar")
        NGOScreen.setStatusBar(self.statusbar)

        self.retranslateUi(NGOScreen)
        QtCore.QMetaObject.connectSlotsByName(NGOScreen)

    def retranslateUi(self, NGOScreen):
        _translate = QtCore.QCoreApplication.translate
        NGOScreen.setWindowTitle(_translate("NGOScreen", "NGO Login"))
        self.label_2.setText(_translate("NGOScreen", "Enter The Following Details To Login As An NGO:"))
        self.label_3.setText(_translate("NGOScreen", "User Name:"))
        self.label_4.setText(_translate("NGOScreen", "Password:"))
        self.NGOEnterButton.setText(_translate("NGOScreen", "Login"))
