# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\NGOSignUp.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NGOSearching(object):
    def setupUi(self, NGOSearching):
        NGOSearching.setObjectName("NGOSearching")
        NGOSearching.resize(520, 397)
        self.centralwidget = QtWidgets.QWidget(parent=NGOSearching)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CreateNGOButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CreateNGOButton.setGeometry(QtCore.QRect(20, 240, 111, 23))
        self.CreateNGOButton.setObjectName("CreateNGOButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 80, 231, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 110, 231, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.label_4.setObjectName("label_4")
        self.ngoSignUpPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ngoSignUpPass.setGeometry(QtCore.QRect(150, 140, 231, 20))
        self.ngoSignUpPass.setObjectName("ngoSignUpPass")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 170, 91, 16))
        self.label_5.setObjectName("label_5")
        self.ngoSignUpConfirmPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ngoSignUpConfirmPass.setGeometry(QtCore.QRect(150, 170, 231, 20))
        self.ngoSignUpConfirmPass.setObjectName("ngoSignUpConfirmPass")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 200, 121, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 81, 16))
        self.label_3.setObjectName("label_3")
        self.ngoSignUpConfirmPass_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ngoSignUpConfirmPass_2.setGeometry(QtCore.QRect(150, 200, 231, 20))
        self.ngoSignUpConfirmPass_2.setObjectName("ngoSignUpConfirmPass_2")
        NGOSearching.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NGOSearching)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 18))
        self.menubar.setObjectName("menubar")
        NGOSearching.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NGOSearching)
        self.statusbar.setObjectName("statusbar")
        NGOSearching.setStatusBar(self.statusbar)

        self.retranslateUi(NGOSearching)
        QtCore.QMetaObject.connectSlotsByName(NGOSearching)

    def retranslateUi(self, NGOSearching):
        _translate = QtCore.QCoreApplication.translate
        NGOSearching.setWindowTitle(_translate("NGOSearching", "NGO Register"))
        self.label.setText(_translate("NGOSearching", "To Sign Up As An NGO, Please Enter The Following Details:"))
        self.CreateNGOButton.setText(_translate("NGOSearching", "CREATE NGO"))
        self.label_2.setText(_translate("NGOSearching", "NGO Name:"))
        self.label_4.setText(_translate("NGOSearching", "Address:"))
        self.label_5.setText(_translate("NGOSearching", "Password:"))
        self.label_6.setText(_translate("NGOSearching", "Confirm Password:"))
        self.label_3.setText(_translate("NGOSearching", "Email Address: "))
