# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\UserSignUp.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminScreen(object):
    def setupUi(self, AdminScreen):
        AdminScreen.setObjectName("AdminScreen")
        AdminScreen.resize(524, 399)
        self.centralwidget = QtWidgets.QWidget(parent=AdminScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 581, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 121, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 70, 231, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 100, 231, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.userSignUpPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userSignUpPass.setGeometry(QtCore.QRect(150, 130, 231, 20))
        self.userSignUpPass.setObjectName("userSignUpPass")
        self.userSignUpConfirmPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userSignUpConfirmPass.setGeometry(QtCore.QRect(150, 160, 231, 20))
        self.userSignUpConfirmPass.setObjectName("userSignUpConfirmPass")
        self.CreateUserButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CreateUserButton.setGeometry(QtCore.QRect(10, 210, 121, 23))
        self.CreateUserButton.setObjectName("CreateUserButton")
        AdminScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=AdminScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 524, 24))
        self.menubar.setObjectName("menubar")
        AdminScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=AdminScreen)
        self.statusbar.setObjectName("statusbar")
        AdminScreen.setStatusBar(self.statusbar)

        self.retranslateUi(AdminScreen)
        QtCore.QMetaObject.connectSlotsByName(AdminScreen)

    def retranslateUi(self, AdminScreen):
        _translate = QtCore.QCoreApplication.translate
        AdminScreen.setWindowTitle(_translate("AdminScreen", "UserRegister"))
        self.label.setText(_translate("AdminScreen", "To Sign Up As A User, Please Enter The Following Details:"))
        self.label_2.setText(_translate("AdminScreen", "User Name:"))
        self.label_3.setText(_translate("AdminScreen", "Email:"))
        self.label_4.setText(_translate("AdminScreen", "Password:"))
        self.label_5.setText(_translate("AdminScreen", "Confirm Password:"))
        self.CreateUserButton.setText(_translate("AdminScreen", "CREATE USER"))
