# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\UserLogin.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserScreen(object):
    def setupUi(self, UserScreen):
        UserScreen.setObjectName("UserScreen")
        UserScreen.resize(451, 333)
        self.centralwidget = QtWidgets.QWidget(parent=UserScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 70, 271, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.userLogInPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.userLogInPass.setGeometry(QtCore.QRect(90, 100, 271, 20))
        self.userLogInPass.setObjectName("userLogInPass")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.pushButton.setObjectName("pushButton")
        UserScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=UserScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 24))
        self.menubar.setObjectName("menubar")
        UserScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=UserScreen)
        self.statusbar.setObjectName("statusbar")
        UserScreen.setStatusBar(self.statusbar)

        self.retranslateUi(UserScreen)
        QtCore.QMetaObject.connectSlotsByName(UserScreen)

    def retranslateUi(self, UserScreen):
        _translate = QtCore.QCoreApplication.translate
        UserScreen.setWindowTitle(_translate("UserScreen", "User Login "))
        self.label.setText(_translate("UserScreen", "Enter The Following Details To Login As A User:"))
        self.label_2.setText(_translate("UserScreen", "User Name:"))
        self.label_3.setText(_translate("UserScreen", "Password:"))
        self.pushButton.setText(_translate("UserScreen", "Login"))
