# Form implementation generated from reading ui file 'c:\Users\murta\NGOConnect\WorkerPage.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 430)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.workerDetails_2 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.workerDetails_2.setGeometry(QtCore.QRect(10, 50, 391, 192))
        self.workerDetails_2.setRowCount(6)
        self.workerDetails_2.setObjectName("workerDetails_2")
        self.workerDetails_2.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.workerDetails_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerDetails_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerDetails_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerDetails_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.workerDetails_2.setHorizontalHeaderItem(4, item)
        self.AddWorkerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.AddWorkerButton.setGeometry(QtCore.QRect(430, 160, 131, 23))
        self.AddWorkerButton.setObjectName("AddWorkerButton")
        self.DeleteWorkerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.DeleteWorkerButton.setGeometry(QtCore.QRect(430, 190, 131, 23))
        self.DeleteWorkerButton.setObjectName("DeleteWorkerButton")
        self.UpdateWorkerButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.UpdateWorkerButton.setGeometry(QtCore.QRect(430, 220, 131, 23))
        self.UpdateWorkerButton.setObjectName("UpdateWorkerButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 251, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.workerDetails_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.workerDetails_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.workerDetails_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.workerDetails_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.workerDetails_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Age"))
        self.AddWorkerButton.setText(_translate("MainWindow", "Add Worker"))
        self.DeleteWorkerButton.setText(_translate("MainWindow", "Remove Worker"))
        self.UpdateWorkerButton.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Details Of All Workers Related To Your NGO:"))
